# ******************************************************************************
#  Oracle WebLogic Server Managed Server Dockerfile.
#
#  Since : February, 2021
#  Author: Arnold Somogyi <arnold.somogyi@gmail.com>
#
#  Copyright (c) 2020-2021 Remal Software and Arnold Somogyi All rights reserved
#  BSD (2-clause) licensed
# ******************************************************************************
FROM docker/remal/oracle-weblogic-managed-with-splunk:1.0.0
LABEL authors="Arnold Somogyi <arnold.somogyi@gmail.com>"

# calling the default CMD command defined in the previous image layer
