# ******************************************************************************
#  Apache-Tomcat compose file.
#
#  Since : February, 2021
#  Author: Arnold Somogyi <arnold.somogyi@gmail.com>
#
#  Copyright (c) 2020 Remal Software and Arnold Somogyi All rights reserved
#  BSD (2-clause) licensed
# ******************************************************************************
version: '3'
services:
    tomcat-server:
        container_name: tomcat-server
        image: docker/images/apache-tomcat-10.0:1.0.0
        ports:
            - "80:8080"
        volumes:
            - ~/dev/workspace/docker/shared-volumes/TOMCAT/upload:/home/tomcat/upload
