# ******************************************************************************
#  Oracle Database Enterprise 12.2.0.1 Docker compose file.
#
#  Since : February, 2021
#  Author: Arnold Somogyi <arnold.somogyi@gmail.com>
#
#  Copyright (c) 2020 Remal Software and Arnold Somogyi All rights reserved
#  BSD (2-clause) licensed
# ******************************************************************************
version: '3'
services:
  oracle-db:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: oracle-db
    ports:
      - "1521:1521" # database listening port
