# ******************************************************************************
#  Compose file for a the hello-weblogic-world application.
#
#  Since : July, 2021
#  Author: Arnold Somogyi <arnold.somogyi@gmail.com>
#
#  Copyright (c) 2020-2021 Remal Software and Arnold Somogyi All rights reserved
#  BSD (2-clause) licensed
# ******************************************************************************
version: '3'
services:
    # ----- WebLogic Admin server ----------------------------------------------
    admin-server:
        image: docker/remal/oracle-weblogic-admin-with-splunk:1.0.0
        container_name: admin-server
        hostname: admin-server
        ports:
            - "7001:7001" # weblogic listening port
            - "4001:4001" # debug port
        command: ["/home/oracle/wait-for-database-and-managed-server.sh", "2"]
        environment:
            - WEB_CONSOLE_COLOR=#9575CD
            - DB_HOST=oracle-db
            - DB_PORT=1521
            - DB_NAME=ORCLPDB1.localdomain
            - DB_USER=SYS as SYSDBA
            - DB_PASSWORD=Oradoc_db1
            - DB_SCHEMA_USER_HELLO=hello
            - DB_SCHEMA_PASSWORD=password
            - CREATE_DATABASE=true
        volumes:
            - ~/dev/workspace/docker/shared-volumes/admin-server/upload:/home/oracle/upload

    # ----- WebLogic Managed servers -------------------------------------------
    hello-welogic-world-managed-server-1:
        image: docker/remal/hello-welogic-world-managed-server:1.0.0
        container_name: managed-server-1
        hostname: managed-server-1
        ports:
            - "8001:8001" # weblogic listening port
            - "5001:4001" # debug port
        volumes:
            - ~/dev/workspace/docker/shared-volumes/managed-server-1/upload:/home/oracle/upload
        command: ["/home/oracle/wait-for-admin-server.sh"]
        environment:
            - ADMIN_SERVER_HOST=admin-server
            - MANAGED_SERVER_NAME=MANAGED_SERVER_1

    hello-welogic-world-managed-server-2:
        image: docker/remal/hello-welogic-world-managed-server:1.0.0
        container_name: managed-server-2
        hostname: managed-server-2
        ports:
            - "8002:8001" # weblogic listening port
            - "5002:4001" # debug port
        volumes:
            - ~/dev/workspace/docker/shared-volumes/managed-server-2/upload:/home/oracle/upload
        command: ["/home/oracle/wait-for-admin-server.sh"]
        environment:
            - ADMIN_SERVER_HOST=admin-server
            - MANAGED_SERVER_NAME=MANAGED_SERVER_2

    # ----- Oracle Database server ---------------------------------------------
    oracle-db:
        image: store/oracle/database-enterprise:12.2.0.1
        container_name: oracle-db
        ports:
            - "1521:1521" # database listening port
