# ******************************************************************************
#  Compose file for an Oracle WebLogic environment with two domains and
#  multiple managed servers.
#
#  Since : February, 2022
#  Author: Arnold Somogyi <arnold.somogyi@gmail.com>
#
#  Copyright (c) 2020-2021 Remal Software and Arnold Somogyi All rights reserved
#  BSD (2-clause) licensed
# ******************************************************************************
version: '3'
services:
    # ----- WebLogic Domain 1 --------------------------------------------------
    weblogic-a-admin-server:
        image: docker/remal/oracle-weblogic-admin-12.2.1.4:2.0.1
        container_name: weblogic-a-admin-server
        hostname: weblogic-a-admin-server
        ports:
            - "7101:7001" # weblogic listening port
            - "4101:4001" # debug port
        environment:
            - MANAGED_SERVER_HOSTNAMES=weblogic-a-managed-server-1, weblogic-a-managed-server-2
            - WEB_CONSOLE_COLOR=#FF5252
        volumes:
            - ~/dev/workspace/docker/shared-volumes/weblogic-a-admin-server-1/upload:/home/oracle/upload

    weblogic-a-managed-server-1:
        image: docker/remal/oracle-weblogic-managed-12.2.1.4:2.0.1
        container_name: weblogic-a-managed-server-1
        hostname: weblogic-a-managed-server-1
        ports:
            - "8101:8001" # weblogic listening port
            - "5101:4001" # debug port
        depends_on:
            - "weblogic-a-admin-server"
        command: ["/home/oracle/wait-for-admin-server.sh"]
        environment:
            - ADMIN_SERVER_HOST=weblogic-a-admin-server
        volumes:
            - ~/dev/workspace/docker/shared-volumes/weblogic-a-managed-server-1/upload:/home/oracle/upload

    weblogic-a-managed-server-2:
        image: docker/remal/oracle-weblogic-managed-12.2.1.4:2.0.1
        container_name: weblogic-a-managed-server-2
        hostname: weblogic-a-managed-server-2
        ports:
            - "8102:8001" # weblogic listening port
            - "5102:4001" # debug port
        depends_on:
            - "weblogic-a-admin-server"
        command: ["/home/oracle/wait-for-admin-server.sh"]
        environment:
            - ADMIN_SERVER_HOST=weblogic-a-admin-server
        volumes:
            - ~/dev/workspace/docker/shared-volumes/weblogic-a-managed-server-2/upload:/home/oracle/upload

    # ----- WebLogic Domain 2 --------------------------------------------------
    weblogic-b-admin-server:
        image: docker/remal/oracle-weblogic-admin-12.2.1.4:2.0.1
        container_name: weblogic-b-admin-server
        hostname: weblogic-b-admin-server
        ports:
            - "7201:7001" # weblogic listening port
            - "4201:4001" # debug port
        environment:
            - MANAGED_SERVER_HOSTNAMES=weblogic-b-managed-server-1, weblogic-b-managed-server-2
            - WEB_CONSOLE_COLOR=#76FF03
        volumes:
            - ~/dev/workspace/docker/shared-volumes/weblogic-b-admin-server-1/upload:/home/oracle/upload

    weblogic-b-managed-server-1:
        image: docker/remal/oracle-weblogic-managed-12.2.1.4:2.0.1
        container_name: weblogic-b-managed-server-1
        hostname: weblogic-b-managed-server-1
        ports:
            - "8201:8001" # weblogic listening port
            - "5201:4001" # debug port
        depends_on:
            - "weblogic-b-admin-server"
        command: ["/home/oracle/wait-for-admin-server.sh"]
        environment:
            - ADMIN_SERVER_HOST=weblogic-b-admin-server
        volumes:
            - ~/dev/workspace/docker/shared-volumes/weblogic-b-managed-server-1/upload:/home/oracle/upload

    weblogic-b-managed-server-2:
        image: docker/remal/oracle-weblogic-managed-12.2.1.4:2.0.1
        container_name: weblogic-b-managed-server-2
        hostname: weblogic-b-managed-server-2
        ports:
            - "8202:8001" # weblogic listening port
            - "5202:4001" # debug port
        depends_on:
            - "weblogic-b-admin-server"
        command: ["/home/oracle/wait-for-admin-server.sh"]
        environment:
            - ADMIN_SERVER_HOST=weblogic-b-admin-server
        volumes:
            - ~/dev/workspace/docker/shared-volumes/weblogic-b-managed-server-2/upload:/home/oracle/upload
