version: "3.6"

services:
  # ----- Splunk ---------------------------------------------------
  splunk:
    image: docker/remal/splunk-8.2:1.0.0
    container_name: splunk
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
    ports:
      - 8000:8000  # splunk default listening port
      - 8088:8088  # HTTP event collector port

  # ----- WebLogic Domain ----------------------------------------------------
  weblogic-admin-server:
    image: docker/remal/oracle-weblogic-admin-with-splunk:1.0.0
    container_name: weblogic-admin-server
    hostname: weblogic-admin-server
    ports:
      - "7001:7001" # weblogic listening port
      - "4001:4001" # debug port
    command: ["/home/oracle/wait-for-managed-server.sh", "2"]
    volumes:
      - ~/dev/workspace/docker/shared-volumes/admin-server/upload:/home/oracle/upload
